import {
  IconAlertCircleFilled,
  IconArrowLeft,
  IconArrowRight,
  IconArrowsDiagonal,
  IconArrowsSort,
  IconBarrierBlock,
  IconBellFilled,
  IconBrandFacebook,
  IconBrandGithub,
  IconBrandLinkedin,
  IconBrandTwitter,
  IconBulb,
  IconCalendar,
  IconChartBar,
  IconCheck,
  IconCircleCheck,
  IconCircleCheckFilled,
  IconCloudUpload,
  IconDatabase,
  IconDatabaseCog,
  IconDatabaseEdit,
  IconDatabaseOff,
  IconDatabasePlus,
  IconDotsVertical,
  IconDownload,
  IconFilePlus,
  IconFileUpload,
  IconFolder,
  IconInfoCircle,
  IconLayoutGrid,
  IconLayoutList,
  IconLayoutSidebarLeftCollapse,
  IconLayoutSidebarLeftExpand,
  IconLink,
  IconLoader,
  IconMenu2,
  IconPencil,
  IconPhoto,
  IconPlus,
  IconSearch,
  IconSettings,
  IconShare3,
  IconShieldCheck,
  IconShieldLock,
  IconShieldStar,
  IconStar,
  IconTerminal,
  IconTrash,
  IconUser,
  IconUserCog,
  IconUsers,
  IconUsersGroup,
  IconWorld,
  IconX,
  // TablerIconsProps,
} from '@tabler/icons-react';

export const Icons: {
  [key: string]: React.FC<any>;
} = {
  access: IconShieldCheck,
  addDataset: IconDatabasePlus,
  alert: IconAlertCircleFilled,
  arrowRight: IconArrowRight,
  back: IconArrowLeft,
  check: IconCircleCheckFilled,
  checkUnfilled: IconCircleCheck,
  collapse: IconLayoutSidebarLeftCollapse,
  construction: IconBarrierBlock,
  cross: IconX,
  dataset: IconDatabase,
  datasetEdit: IconDatabaseEdit,
  datasetSettings: IconDatabaseCog,
  delete: IconTrash,
  distribution: IconFilePlus,
  download: IconDownload,
  dropzone: IconCloudUpload,
  errorPage: IconDatabaseOff,
  expand: IconLayoutSidebarLeftExpand,
  facebook: IconBrandFacebook,
  fileUpload: IconFileUpload,
  github: IconBrandGithub,
  info: IconInfoCircle,
  link: IconLink,
  linkedin: IconBrandLinkedin,
  logo: IconFolder,
  menu: IconMenu2,
  notification: IconBellFilled,
  openAccess: IconShieldCheck,
  pencil: IconPencil,
  plus: IconPlus,
  registeredAccess: IconShieldStar,
  restrictedAccess: IconShieldLock,
  search: IconSearch,
  share: IconShare3,
  terminal: IconTerminal,
  twitter: IconBrandTwitter,
  checkmark: IconCheck,
  loader: IconLoader,
  userList: IconUsers,
  userSettings: IconUserCog,
  arrowDiagonal: IconArrowsDiagonal,
  verticalDots: IconDotsVertical,
  chart: IconChartBar,
  list: IconLayoutList,
  grid: IconLayoutGrid,
  calendar: IconCalendar,
  globe: IconWorld,
  diagonal: IconArrowsDiagonal,
  sort: IconArrowsSort,
  user: IconUser,
  userGroup: IconUsersGroup,
  setting: IconSettings,
  photo: IconPhoto,
  star: IconStar,
  light: IconBulb,
};
