import {
  IconArrowLeft,
  IconArrowRight,
  IconBarrierBlock,
  IconBellFilled,
  IconBrandFacebookFilled,
  IconBrandGithubFilled,
  IconBrandLinkedin,
  IconBrandTwitterFilled,
  IconCircleCheckFilled,
  IconCloudUpload,
  IconDatabase,
  IconDatabaseCog,
  IconDatabaseEdit,
  IconDatabasePlus,
  IconDownload,
  IconFilePlus,
  IconFileUpload,
  IconFolder,
  IconInfoCircle,
  IconLayoutSidebarLeftCollapse,
  IconLayoutSidebarLeftExpand,
  IconLink,
  IconMenu2,
  IconPencil,
  IconPlus,
  IconSearch,
  IconShare3,
  IconShieldCheck,
  IconShieldLock,
  IconShieldStar,
  IconTerminal,
  IconTrash,
  IconUserCog,
  IconUsers,
  IconX,
  // TablerIconsProps,
} from '@tabler/icons-react';

export const Icons: {
  [key: string]: React.FC<any>;
} = {
  back: IconArrowLeft,
  logo: IconFolder,
  datasetSettings: IconDatabaseCog,
  datasetEdit: IconDatabaseEdit,
  userList: IconUsers,
  dataset: IconDatabase,
  addDataset: IconDatabasePlus,
  userSettings: IconUserCog,
  arrowRight: IconArrowRight,
  search: IconSearch,
  notification: IconBellFilled,
  info: IconInfoCircle,
  construction: IconBarrierBlock,
  link: IconLink,
  collapse: IconLayoutSidebarLeftCollapse,
  expand: IconLayoutSidebarLeftExpand,
  distribution: IconFilePlus,
  dropzone: IconCloudUpload,
  check: IconCircleCheckFilled,
  delete: IconTrash,
  terminal: IconTerminal,
  cross: IconX,
  menu: IconMenu2,
  access: IconShieldCheck,
  openAccess: IconShieldCheck,
  registeredAccess: IconShieldStar,
  restrictedAccess: IconShieldLock,
  share: IconShare3,
  pencil: IconPencil,
  fileUpload: IconFileUpload,
  plus: IconPlus,
  twitter: IconBrandTwitterFilled,
  facebook: IconBrandFacebookFilled,
  linkedin: IconBrandLinkedin,
  github: IconBrandGithubFilled,
  download: IconDownload,
};
